graph TD
    A[Root Project]
    A --> B[setup.cfg]
    A --> C[example.py]
    A --> D[.gitignore]
    A --> E[README.md]
    A --> F[pyproject.toml]

    A --> G[test_doc]
    G --> G1[hnw14-vdw79.doc]
    G --> G2[a15a2-6pwn0.doc]

    A --> H[zddoc]
    H --> H1[cli.py]
    H --> H2[piece_table.py]
    H --> H3[reader.py]
    H --> H4[fib.py]
    H --> H5[cfbf.py]

    A --> I[tests]
    I --> I1[test_core.py]